# This is your Fastfile located at ./fastlane/Fastfile

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Sync certificates and provisioning profiles using match
    match(type: "appstore")

    # Build your app
    build_app(
      workspace: "Runner.xcworkspace", 
      scheme: "Runner"
    )

    # Upload to TestFlight
    upload_to_testflight
  end
end
