# This is your Fastfile located at ./fastlane/Fastfile

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "84AG5LAL42",
      issuer_id: "aaf8a98f-bbd1-47cd-81ff-f1e98ad51d13",
      is_key_content_base64: true,
      key_content: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR1RBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJIa3dkd0lCQVFRZ3JueVRqaG5MRjhqQWpKeTEKVUNSWHN2RXZhR2JrN2NhQXovd01WMUhsSVdLZ0NnWUlLb1pJemowREFRZWhSQU5DQUFTNkxOOGlBMzlNRjBZNwpUODd6bEVIY0Fzekc5OEZMOHFOMVRPUnJvQ2ZWdlJZUE1rUXEvME4yWGtpZFdiY3MxUGxIV2FveXBJY093SEh1CnMzekxwb1hZCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=",
      in_house: false,
    )
    # Sync certificates and provisioning profiles using match
    match(
      type: "appstore",
      api_key: api_key,
      keychain_password: ENV['KEYCHAIN_PASSWORD'] # Set the keychain password here
    )
    # Build your app
    build_app(
      workspace: "Runner.xcworkspace", 
      scheme: "Runner"
    )

    # Upload to TestFlight
    upload_to_testflight(api_key: api_key)
  end
end
