# This is your Fastfile located at ./fastlane/Fastfile

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "84AG5LAL42",
      issuer_id: "aaf8a98f-bbd1-47cd-81ff-f1e98ad51d13",
      is_key_content_base64: false,
      key: "-----BEGIN PRIVATE KEY-----
      MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgrnyTjhnLF8jAjJy1
      UCRXsvEvaGbk7caAz/wMV1HlIWKgCgYIKoZIzj0DAQehRANCAAS6LN8iA39MF0Y7
      T87zlEHcAszG98FL8qN1TORroCfVvRYPMkQq/0N2XkidWbcs1PlHWaoypIcOwHHu
      s3zLpoXY
      -----END PRIVATE KEY-----"
    )
    # Sync certificates and provisioning profiles using match
    match(type: "appstore", api_key: app_store_connect_api_key)

    # Build your app
    build_app(
      workspace: "Runner.xcworkspace", 
      scheme: "Runner"
    )

    # Upload to TestFlight
    upload_to_testflight(api_key: app_store_connect_api_key)
  end
end
