name: Flutter CI/CD

on:
  push:
    branches:
      - signal-r

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Install Xcode Command Line Tools
      run: xcode-select --install || true

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.9' # use the version you need

    - name: Install dependencies
      run: flutter pub get

    - name: Install CocoaPods dependencies
      run: cd ios && pod install && cd ..

    - name: Install Fastlane
      run: |
        brew install ruby
        gem install fastlane -NV

    - name: Run Fastlane
      run: |
        cd ios
        fastlane beta
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
