name: Flutter CI/CD

on:
  push:
    branches:
      - signal-r

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.9' # use the version you need

    - name: Install dependencies
      run: flutter pub get

    - name: Install CocoaPods dependencies
      run: cd ios && pod install && cd ..

    - name: Build iOS
      run: flutter build ios --release --no-codesign

    - name: Enable Automatic Signing
      run: |
        xcodebuild -project ios/Runner.xcodeproj -scheme Runner -destination 'generic/platform=iOS' -allowProvisioningUpdates
        
    - name: Install Apple certificate and provisioning profile
      env:
        APPLE_CERTIFICATE: MIIM2wIerwt
        P12_PASSWORD: myyyynewwwkeyychaaainnpass
        PROVISIONING_PROFILE: MIIviQYSlAh3Ng=
        KEYCHAIN_PASSWORD: 745HX£325FH!
      run: |
        # create variables
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

        # import certificate and provisioning profile from secrets
        echo -n "$APPLE_CERTIFICATE" | base64 --decode -o $CERTIFICATE_PATH
        echo -n "$PROVISIONING_PROFILE" | base64 --decode -o $PP_PATH

        # create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

        # import certificate to keychain
        security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH

        # apply provisioning profile
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

    - name: Deploy to TestFlight
      run: |
        # Build IPA
        xcodebuild clean -workspace "ios/Runner.xcworkspace" -scheme "Runner" -configuration Release
        xcodebuild archive -workspace "ios/Runner.xcworkspace" -scheme "Runner" -configuration Release -archivePath "build/ios/Runner.xcarchive"
        xcodebuild -exportArchive -archivePath "build/ios/Runner.xcarchive" -exportOptionsPlist "exportOptions.plist" -exportPath "build/ios/"

        # Upload to TestFlight
        altool --upload-app -f "build/ios/Runner.ipa" -t ios -u mmk100@mail.aub.edu -p hveh-blaw-okdn-anbuc --verbose
      env:
        ITC_USER: mmk100@mail.aub.edu
        ITC_APP_SPECIFIC_PASSWORD: hveh-blaw-okdn-anbuc
